name: Release

on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.3.1
      with:
        # For an on-PR workflow, it would normally checkout a merge commit of the PR branch
        # into the base branch. Instead we want the tip of the PR branch:
        ref: ${{ github.head_ref }}

    - name: Configure git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        echo " "
        git status
        echo " "
        git log --graph --oneline --decorate --all


    - name: Write current date in foo.md
      run: |
        date_now=$(date '+%Y-%m-%d %H:%M:%S' --utc)
        sed -i "s|<!-- ACTIONS.BIND: date -->|$date_now|" foo.md

    - name: Commit & push
      run : |
        git commit -S -a -m "Write current date" -m "Workflow: ${{ github.workflow }}, run: ${{ github.run_number }}"
        echo " "
        git log --graph --oneline --decorate --all
        echo " "
        git push origin ${{ github.head_ref }}

